### ISSUE TITLE
PXF External Table Hive 3.1 failed with java.io.IOException: Not a file

### ISSUE THREAD

**Issue by timofreenet** [greenplum-db/pxf#97] opened 2019-02-21 14:05 UTC
### HDP 3.1 / Hive 3.1
Hive:
CREATE TABLE sales_info (location string, month string, number_of_orders int, total_sales double)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS textfile;

select * from sales_info;
+----------------------+-------------------+------------------------------+-------------------------+
| sales_info.location | sales_info.month | sales_info.number_of_orders | sales_info.total_sales |
+----------------------+-------------------+------------------------------+-------------------------+
| Prague | Jan | 101 | 4875.33 |
| Rome | Mar | 87 | 1557.39 |
| Bangalore | May | 317 | 8936.99 |
| Beijing | Jul | 411 | 11600.67 |
| San Francisco | Sept | 156 | 6846.34 |
| Paris | Nov | 159 | 7134.56 |
| San Francisco | Jan | 113 | 5397.89 |
| Prague | Dec | 333 | 9894.77 |
| Bangalore | Jul | 271 | 8320.55 |
| Beijing | Dec | 100 | 4248.41 |
+----------------------+-------------------+------------------------------+-------------------------+
Greenplum:
CREATE EXTERNAL TABLE salesinfo_hivetextprofile(location text, month text, num_orders int, total_sales float8)
LOCATION ('pxf://default.sales_info?PROFILE=HiveText&DELIMITER=\x2c')
FORMAT 'TEXT' (delimiter=E',');

select * from salesinfo_hivetextprofile; ERROR: remote component error (500) from '127.0.0.1:5888': type Exception report message javax.servlet.ServletException: java.io.IOException: Not a file: hdfs://hdm1-t.aq3hcc40qdkurot1542u4kjxfd.ax.internal.cloudapp.net:8020/warehouse/tablespace/managed/hive/sales_info/delta_0000001_0000001_0000 description The server encountered an internal error that prevented it from fulfilling this request. exception javax.servlet.ServletException: javax.servlet.ServletException: java.io.IOException: Not a file: hdfs://hdm1-t.aq3hcc40qdkurot1542u4kjxfd.ax.internal.cloudapp.net:8020/warehouse/tablespace/managed/hive/sales_info/delta_0000001_0000001_0000 (libchurl.c:944) (seg0 slice1 172.16.0.7:6000 pid=52329) (cdbdisp.c:254)
DETAIL: External table salesinfo_hivetextprofile, file pxf://default.sales_info?PROFILE=HiveText&DELIMITER=\x2c

PXF log:
Feb 20, 2019 2:46:54 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
java.io.IOException: Not a file: hdfs://hdm1-t.aq3hcc40qdkurot1542u4kjxfd.ax.internal.cloudapp.net:8020/warehouse/tablespace/managed/hive/sales_info/delta_0000001_0000001_0000
at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:329)
at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.fetchMetaData(HiveDataFragmenter.java:302)
at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.fetchMetaDataForSimpleTable(HiveDataFragmenter.java:263)
at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.fetchMetaDataForSimpleTable(HiveDataFragmenter.java:257)
at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.fetchTableMetaData(HiveDataFragmenter.java:229)
at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.getFragments(HiveDataFragmenter.java:124)
at org.greenplum.pxf.service.rest.FragmenterResource.getFragments(FragmenterResource.java:92)
at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.greenplum.pxf.service.servlet.SecurityServletFilter.lambda$doFilter$0(SecurityServletFilter.java:105)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
at org.greenplum.pxf.service.servlet.SecurityServletFilter.doFilter(SecurityServletFilter.java:120)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)

**Comment by timofreenet** [comment] 2019-02-21 17:07
The support of the currently used standard Hive versions provides a fundamentally necessary functionality.
The Hortonworks HDP 2.5 support will be discontinued mid-year and HDP 2.6 by the end of the year. Thus there is no support for Hive 1.x and Hive 2.x at the end of the year.
Therefore, the support of Hive 3.x within PXF should be prioritized accordingly.

**Comment by frankgh** [comment] 2019-02-22 05:05
@timofreenet thanks for the feedback, we are in the process of exploring the upgrade to Hive 3.

**Comment by timofreenet** [comment] 2019-04-08 09:30
@frankgh nay news about the support of Hive 3.x within PXF?

**Comment by frankgh** [comment] 2019-04-19 15:32
@vraghavan78 can you follow up with this issue.

**Comment by frankgh** [comment] 2019-09-25 16:16
Hive 3 support added in https://github.com/greenplum-db/pxf/pull/230 and certified in https://github.com/greenplum-db/pxf/pull/235. Support for Hive 3 in PXF version 5.9.0

**Comment by ururu-fy** [comment] 2019-10-03 14:19
Hello.
I have compiled last master. But I still have a problem with hive external table.

SQL Error [XX000]: ERROR: remote component error (500) from '127.0.0.1:5888':  Type  Exception Report   Message  javax.servlet.ServletException: java.io.IOException: Not a file: hdfs://DevDataLake3NNHA/warehouse/tablespace/managed/hive/sales_info/delta_0000001_0000001_0000   Description  The server encountered an unexpected condition that prevented it from fulfilling the request.   Exception   javax.servlet.ServletException: javax.servlet.ServletException: java.io.IOException: Not a file: hdfs://DevDataLake3NNHA/warehouse/tablespace/managed/hive/sales_info/delta_0000001_0000001_0000 (libchurl.c:920)  (seg0 slice1 10.243.209.132:6000 pid=31539) (libchurl.c:920)
  Where: External table salesinfo_hivetextprofile, line 1 of file pxf://default.sales_info?PROFILE=HiveText

**Comment by frankgh** [comment] 2019-10-03 14:36
@ururu-fy can you provide the Hive table DDL and the Greenplum table DDL? 

Thank you

**Comment by ururu-fy** [comment] 2019-10-04 08:11
Sure.
Hive table ddl
```
CREATE TABLE `default.sales_info`(
  `location` string, 
  `month` string, 
  `number_of_orders` int, 
  `total_sales` double)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
WITH SERDEPROPERTIES ( 
  'field.delim'=',', 
  'serialization.format'=',') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  'hdfs://DevDataLake3NNHA/warehouse/tablespace/managed/hive/sales_info'
TBLPROPERTIES (
  'bucketing_version'='2', 
  'transactional'='true', 
  'transactional_properties'='insert_only', 
  'transient_lastDdlTime'='1570011168')
```

Greenplum table ddl
```
CREATE EXTERNAL TABLE gpadmin.public.salesinfo_hivetextprofile (
	location text,
	month text,
	num_orders int4,
	total_sales float8
)
LOCATION (
	'pxf://default.sales_info?PROFILE=HiveText'
) ON ALL
FORMAT 'TEXT' ( delimiter ',' null '\N' escape '\' )
ENCODING 'UTF8';
```

**Comment by denalex** [comment] 2019-10-04 22:20
@ururu-fy -- PXF does not support ACID (transactional) tables `TBLPROPERTIES ('transactional'='true')` in Hive 3 via `Hive` profile due to the fact that the HDFS storage layout for these tables is more complex, includes `delta` directories (source of the problem here) and requires special readers. You still should be able to access these tables via JDBC profile with Hive JDBC driver.

@timofreenet -- you had the same problem, but your table is not explicitly declaring transactional properties. How did it get populated with values ? Somehow it was written by ACID-enabled writer that created `delta` directories.

**Comment by ururu-fy** [comment] 2019-10-05 15:07
I understood, thank you for explain. Ok. 
Can I use transactional table with hive orc format? 
I created hive orc format table and I didn't have  error "IOException: Not a file".  But when I have queried an external table  I haven't had data.
For example:
hive ddl
```
CREATE TABLE `default.sales_info_orc`(
  `location` string,
  `month` string,
  `number_of_orders` int,
  `total_sales` double)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
  'hdfs://DevDataLake3NNHA/warehouse/tablespace/managed/hive/sales_info_orc'
TBLPROPERTIES (
  'bucketing_version'='2',
  'transactional'='true',
  'transactional_properties'='default',
  'transient_lastDdlTime'='1570273629')
```
 
hive table data
an           101         4875      
Rome    Mar       87           1557.39
Bangalore           May       317         8936.99
Beijing  Jul          411         11600.67
San Francisco    Sept       156         6846.34
Paris      Nov       159         7134.56
San Francisco    Jan         113         5397.89
Prague Dec        333         9894.77
Bangalore           Jul           271         8320.55
Beijing  Dec        100         4248.41
 
 Greenplum ddl
```
CREATE TABLE public.salesinfo_hiveorcprofile (
       "location" text NULL,
       "month" text NULL,
       num_orders int4 NULL,
       total_sales float8 NULL
)
DISTRIBUTED RANDOMLY;
```

pxf-service.log:
2019-10-05 16:05:53.0242 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.materializedview.rewriting.incremental does not exist                                               
2019-10-05 16:05:53.0242 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.server2.webui.cors.allowed.headers does not exist                                                   
2019-10-05 16:05:53.0242 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.hook.proto.base-directory does not exist                                                            
2019-10-05 16:05:53.0242 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.load.data.owner does not exist                                                                      │
2019-10-05 16:05:53.0242 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.service.metrics.codahale.reporter.classes does not exist                                            
2019-10-05 16:05:53.0242 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.strict.managed.tables does not exist                                                                │
2019-10-05 16:05:53.0243 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.create.as.insert.only does not exist                                                                │
2019-10-05 16:05:53.0243 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.metastore.db.type does not exist                                                                    │
2019-10-05 16:05:53.0243 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.tez.cartesian-product.enabled does not exist                                                        
2019-10-05 16:05:53.0243 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.metastore.warehouse.external.dir does not exist                                                     
2019-10-05 16:05:53.0243 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.heapsize does not exist                                                                             │
2019-10-05 16:05:53.0243 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.server2.enable.impersonation does not exist                                                         
2019-10-05 16:05:53.0243 WARN tomcat-http--1 org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.server2.webui.enable.cors does not exist                                                            
2019-10-05 16:05:53.0474 INFO tomcat-http--16 org.greenplum.pxf.service.rest.FragmenterResource - org.greenplum.pxf.plugins.hive.HiveInputFormatFragmenter returns 0 fragments for path default.sales_info_orc│
in 314 ms for Session = gpadmin:1569409667-0000018511:2 [profile HiveORC filter is not available]                                                                                                            │
2019-10-05 16:05:53.0474 INFO tomcat-http--1 org.greenplum.pxf.service.rest.FragmenterResource - org.greenplum.pxf.plugins.hive.HiveInputFormatFragmenter returns 0 fragments for path default.sales_info_orc │
in 314 ms for Session = gpadmin:1569409667-0000018511:0 [profile HiveORC filter is not available]                                                                                                             │
2019-10-05 16:05:53.0474 INFO tomcat-http--2 org.greenplum.pxf.service.rest.FragmenterResource - org.greenplum.pxf.plugins.hive.HiveInputFormatFragmenter returns 0 fragments for path default.sales_info_orc │
in 314 ms for Session = gpadmin:1569409667-0000018511:1 [profile HiveORC filter is not available]          
 
I have  hive-site.xml  in pxf/conf/servers/default and it contain this parameters.

**Comment by denalex** [comment] 2019-10-07 03:24
@ururu-fy -- I don't think Hive ORC will work either, according to http://shzhangji.com/blog/2019/06/10/understanding-hive-acid-transactional-table/ as it will likely also create `delta` directories.

In your example you did not get an error or any result because the Fragmenter did not find any data for your table. How did you insert the data into the Hive table ? What is the current layout of your data in HDFS directory `hdfs://DevDataLake3NNHA/warehouse/tablespace/managed/hive/sales_info_orc` ?

We can try to reproduce this on our side, if you can provide us with:
- DML to load your data into Hive (or an existing ORC file)
- `hive-site.xml` for your Hive installation

**Comment by ururu-fy** [comment] 2019-10-08 14:16
There was a problem in the transactional table. With  non transactional  everything work fine. Thank you.

**Comment by denalex** [comment] 2019-10-08 23:33
In summary:
- PXF Hive profile can be used to read only from non-transactional tables in Hive3
- by default in HDP 3.1 distribution, any managed non-temporary table in Hive3 becomes transactional
- to make sure managed tables do not become transactional by default, set the following properties for your Hive installation's `hive-site.xml` :
```
hive.strict.managed.tables = false
hive.create.as.insert.only = false
metastore.create.as.acid = false
```
- when creating tables in Hive, do not specify transactional properties for the tables, then PXF should still be able to read them

For the reference, the property `hive.strict.managed.tables` is set to `false` in standard Hive distribution: https://github.com/apache/hive/blob/2d99f7863f9da49ef56a85ae156f4bd4b9d5802b/common/src/java/org/apache/hadoop/hive/conf/HiveConf.java#L3052

I will be closing the issue, please re-open if you have further questions.

**Closed by denalex** 2019-10-08 23:33 UTC
