### ISSUE TITLE
insert into pxf_table select * from db2_table

### ISSUE THREAD

**Issue by timeobserver** [greenplum-db/pxf#452] opened 2020-09-18 00:44 UTC
I use pxf pull data from db2 to greenplum,
greenplum version is 5.14 , 
db2 version is v11.1,
pxf version is 4.0.3;

when the db2 column type is int or bigint and the column is null in the db2 table , after execute insert into pxf_table select * from db2_table, data which is null automatically converted to 0 .  

wish your help ,thanks!

**Comment by timeobserver** [comment] 2020-09-18 00:48
i don't know whether the latest greenplum and pxf version also has  this issue ,  or how can i avert this question.

**Comment by frankgh** [comment] 2020-09-19 15:25
@timeobserver this issue has been fixed in newer versions of PXF (Fixed in #108). The fixed issue is: `assign null to oneField.val if result.wasNull(), otherwise use the value`. It corresponds to this line in the code: https://github.com/greenplum-db/pxf/blob/master/server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcResolver.java#L132.

The fix is only available in version 5.1.0 of PXF, that's a pretty old version of PXF, so I suggest you upgrade to a later version. You will probably need to upgrade Greenplum to be able to upgrade PXF.

**Closed by frankgh** 2020-09-19 15:25 UTC

**Comment by frankgh** [comment] 2020-09-19 15:28
By the way, I tested this in the latest version of PXF and I can confirm that the issue is fixed:

**DB2**
```
db2 => create table int_bigint (a int, b bigint)
DB21034E  The command was processed as an SQL statement because it was not a
valid Command Line Processor command.  During SQL processing it returned:
SQL1024N  A database connection does not exist.  SQLSTATE=08003
db2 => connect to testdb

   Database Connection Information

 Database server        = DB2/LINUXX8664 11.5.4.0
 SQL authorization ID   = DB2INST1
 Local database alias   = TESTDB

db2 => create table int_bigint (a int, b bigint)
DB20000I  The SQL command completed successfully.
db2 => insert into int_bigint values (5, 132423432423)
DB20000I  The SQL command completed successfully.
db2 => insert into int_bigint values (null, 534553242314)
DB20000I  The SQL command completed successfully.
db2 => insert into int_bigint values (32, null)
DB20000I  The SQL command completed successfully.
db2 => select * from int_bigint

A           B
----------- --------------------
          5         132423432423
          -         534553242314
         32                    -

  3 record(s) selected.
```

**Greenplum**
```
  aguerrero-a01 in ~/workspace/scripts
○ → createdb db2

  aguerrero-a01 in ~/workspace/scripts
○ → psql !$
psql db2
psql (9.4.24)
Type "help" for help.

db2=# create extension pxf;
CREATE EXTENSION
db2=# create external table db2_int_null (a int, b bigint)
db2-# location ('pxf://int_bigint?PROFILE=jdbc&SERVER=db2')
db2-# format 'custom' (formatter='pxfwritable_import');
CREATE EXTERNAL TABLE
db2=# \d                                                                                                                                       List of relations
 Schema |     Name     | Type  |   Owner   | Storage
--------+--------------+-------+-----------+----------
 public | db2_int_null | table | fguerrero | external
(1 row)

db2=# select * from db2_int_null ;
 a  |      b
----+--------------
  5 | 132423432423
    | 534553242314
 32 |
(3 rows)
```

**Comment by frankgh** [comment] 2020-09-19 15:32
maybe this output is better:
```
db2=# \pset null [null];
db2=# select * from db2_int_null ;
   a    |      b
--------+--------------
      5 | 132423432423
 [null] | 534553242314
     32 |       [null]
(3 rows)

Time: 3169.713 ms
```
